title: Companion Website for <i>A Practical Guide to Observational Astronomy</i> 
description:  by [M. Shane Burns](https://faculty1.coloradocollege.edu/~sburns/)
show_downloads: false
theme: jekyll-theme-slate
